/*
 * Copyright (c) 2018. 7Summits Inc.
 */

/**
 * Created by francois korb on 3/16/18.
 */

global with sharing class SVNSUMMITS_Members_TestConstants
{
	// Profiles
	static final global String COMPANY_COMMUNITY_PROFILE_NAME = 'Customer Community User';
	static final global String PARTNER_COMMUNITY_PROFILE_NAME = 'Partner Community User';

//	Topics
	static final global Integer TEST_TOPIC_COUNT = 3;
}