/* Copyright ©2016-2018 7Summits Inc. All rights reserved. */

/**
 * Created by francoiskorb on 3/14/18.
 */

public with sharing class SVNSUMMITS_Event_TestConstants
{
	// These profiles are assumed to have full access to the 7S Event__c and related objects
	public static final String CUSTOMER_COMMUNITY_USER	     = '7S Customer Community Login User';
	public static final String CUSTOMER_COMMUNITY_USER_CLONE = '7S Customer Community Login User';
}