/*
 * Copyright (c) 2020. 7Summits Inc.
 */


public with sharing class x7sAdventureCloneTestConstants {

	public static final String ACCOUNT_NAME = 'Test Account';

	public static final String TEST_URL = 'http://7summitsinc.com';
	public static final String TEST_ADVENTURE_NAME = 'Test Adventure';
	public static final String TEST_ADVENTURE_STEP_NAME = 'Test Adventure Step';
	public static final String TEST_ADVENTURE_STEP_SUBTITLE = 'Test Adventure Step Subtitle';
	public static final String TEST_ADVENTURE_STEP_DESCRIPTION = 'Test Description ';
	public static final Boolean TEST_TEMPLATE_NAME = true;

	public static final String TEST_STEP_MODULE_NAME = 'Test Step Module';

	public static final String TEST_MODULE_TASK_NAME = 'Test Module Task';
	public static final Boolean TEST_MODULE_TASK_RESTRICT_TO_USER = true;
	public static final String TEST_RESOURCE_TYPE = 'Salesforce';

	public static final String TEST_CONTENT_VERSION_TITLE = 'Test Document';
	public static final String TEST_CONTENT_VERSION_PATH_ON_CLIENT = 'TestDocument.pdf';
	public static final Blob TEST_CONTENT_VERSION_VERSION_DATA = Blob.valueOf('Test Content');
	public static final Boolean TEST_CONTENT_VERSION_IS_MAJOR_VERSION = true;
}