/*
 * Copyright (c) 2021. 7Summits, an IBM Company. All rights reserved.
 */

public with sharing class x7sFilesConstants {

    //Filter Constants
    public static final String EQUALS_OPERATOR = ' = ';
    public static final String NOT_EQUALS_OPERATOR = ' != ';
    public static final String GREATER_EQUAL_OPERATOR = ' >= ';
    public static final String GREATER_THAN_OPERATOR = ' > ';
    public static final String LESS_EQUAL_OPERATOR = ' <= ';
    public static final String LESS_THAN_OPERATOR = ' < ';
    public static final String INCLUDES_OPERATOR = ' INCLUDES ';
    public static final String EXCLUDES_OPERATOR = ' EXCLUDES ';
    public static final String CONTAINS_OPERATOR = ' LIKE ';
    public static final String NOT_CONTAINS_OPERATOR = ' NOT ';
    public static final String BETWEEN_OPERATOR = 'Between';

    //List Constants
    public static final Integer QueryLimit = 50000;
}